networks:
  default:
    external:
      name: dy
services:
  mongodb:
    image: mongo:3
    volumes:
      - ./db:/data/db
  locomotive:
    image: quay.io/akretion/locomotive-shopinvader-demo:v3.4-latest
    environment:
      - VIRTUAL_HOST=locomotive-shopinvader-demo.dy
      - VIRTUAL_PORT=3000
      - RAILS_ENV=development
      - STORE_ASSET_IN_S3=false
      - DRAGON_FLY_SECRET=thisISaDEMOkeyNOTsecret
      - MONGODB_DEV_HOST=mongodb
      - LOCOMOTIVE_ENABLE_REGISTRATION=true
    volumes:
      - usr_src_app_log:/usr/src/app/tmp
      - usr_src_app_tmp:/usr/src/app/log
      - usr_src_app_public_sites:/usr/src/app/public/sites
      - usr_src_app_public_uploaded:/usr/src/app/public/uploaded_assets
    depends_on:
      - mongodb
version: '3'
volumes:
  usr_src_app_log:
  usr_src_app_tmp:
  usr_src_app_public_sites:
  usr_src_app_public_uploaded:

