services:
  db_mongo:
    image: mongo:3
    volumes:
      - mg_volume:/data/db
  locomotive:
    image: quay.io/akretion/shopinvader:v3.4.x-20181107
    env_file: environment
#    links:
#      - db_mongo
#      - odoo
    ports:
      - 3000:3000
    volumes:
      - usr_src_app_log:/usr/src/app/log
      - usr_src_app_tmp:/usr/src/app/tmp
      - usr_src_app_public_sites:/usr/src/app/public/sites
      - usr_src_app_public_uploaded:/usr/src/app/public/uploaded_assets
      - usr_local_bundle:/usr/local/bundle
  wagon:
    image: quay.io/akretion/shopinvader-wagon:v3.4.x-2018110702
#    links:
#    - locomotive
    volumes:
      - ./template:/workspace
  db_postgresql:
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_DB=db
    image: quay.io/akretion/postgresql:10
    volumes:
      - pg_volume:/var/lib/postgresql/data
  odoo:
    ports:
      - 8069:8069
      - 8072:8072
      - 8071:8071
    environment:
      - DB_HOST=db_postgresql
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=db2
      - DB_FILTER=
      - ADMIN_PASSWD=admin
      - DEMO=true
      - SERVER_WIDE_MODULES=web,web_kanban,queue_job
      - ADDONS_PATH=/odoo/src/addons,odoo/src/odoo/addons,/odoo/links,/odoo/external-src/odoo-shopinvader,/odoo/external-src/connector-search-engine,/odoo/external-src/bank-payment,/odoo/external-src/product-brand,/odoo/external-src/rest-framework,/odoo/external-src/sale-workflow,/odoo/external-src/queue,/odoo/external-src/product-variant,/odoo/external-src/server-tools,/odoo/external-src/delivery-carrier,/odoo/external-src/payment-gateway,/odoo/external-src/storage,/odoo/external-src/connector,/odoo/external-src/e-commerce,/odoo/external-src/ak-odoo-incubator,/odoo/external-src/crm,/odoo/external-src/account-reconcile
    image: shopinvader_all_in_one 
#    image: quay.io/akretion/shopinvader-odoo:latest
#    links:
#    - db_postgresql
#    - locomotive
version: '3'
volumes:
  usr_src_app:
  usr_local_bundle:
  usr_src_app_log:
  usr_src_app_tmp:
  usr_src_app_public_sites:
  usr_src_app_public_uploaded:
  pg_volume:
  mg_volume:
