services:
  db_mongo:
    image: mongo:3
  locomotive:
    image: quay.io/akretion/locomotive:master
    env_file: environment
    links:
      - db_mongo
    image: quay.io/akretion/shopinvader:master
    ports:
      - 3000:3000
  wagon:
    image: quay.io/akretion/shopinvader-wagon:latest
    links:
      - locomotive
    volumes:
    - ./template:/workspace
version: '3'
