services:
  db_mongo:
    image: mongo:3
    volumes:
      - ./data/mongo/db:/data/db
      - ./data/mongo/db/backup:/backup
  locomotive:
    image: quay.io/akretion/locomotive:master
    env_file: environment
    links:
      - db_mongo
    image: quay.io/akretion/shopinvader:section
    volumes:
      - ./data/loco/log:/usr/src/app/log
      - ./data/loco/tmp:/usr/src/app/tmp
  wagon:
    image: quay.io/akretion/shopinvader-wagon:latest
    links:
      - locomotive
    volumes:
    - template:/workspace

version: '3'